version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: auth_rbac_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: auth_rbac
    ports:
      - "5432:5432"
    volumes:
      - auth_rbac_postgres_data:/var/lib/postgresql/data

volumes:
  auth_rbac_postgres_data:
