GET http://localhost:3000

###
POST http://localhost:3000/users/register
content-type: application/json

{
  "name": "joao",
  "email": "joao@teste.com",
  "password": "123456",
  "phoneNumber": "51999998866"
}

###
POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "joao@teste.com",
  "password": "123456"
}

###
POST http://localhost:3000/auth/recover-password
content-type: application/json

{
  "email": "teste2@teste.com"
}

###
POST http://localhost:3000/auth/reset-password
content-type: application/json

{
  "email": "teste2@teste.com",
  "token": "5b03cbbc-9b7c-4de4-8832-f945a9d9be0e",
  "password": "654321"
}

### TOKEN EXPIRADO para negar o acesso
GET http://localhost:3000/users/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIxMTg3NjQ0LTQxZjEtNGYwZS1hZWU0LTQzNGYxMjBiMjcxZiIsIm5hbWUiOiJzYW1wbGVzIiwiZW1haWwiOiJ0ZXN0ZTJAdGVzdGUuY29tIiwicGhvbmVOdW1iZXIiOiI1MTk5OTk5ODg3NyIsInByb2ZpbGVQaWN0dXJlIjpudWxsLCJhY3RpdmUiOnRydWUsImlhdCI6MTczNTg0MzcwOCwiZXhwIjoxNzM1ODU4MTA4fQ.Bpb_DJf9sNZbGCdBV9U6GYkJM2lWM_OmAJYUkcBebKg

### TOKEN COM ACESSO
GET http://localhost:3000/users/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiYmI4MjBjLWQ0ODMtNDlmNS04NmQ5LTNiMmQyNzE4NzFiMyIsIm5hbWUiOiJqb2FvIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsInBob25lTnVtYmVyIjoiNTE5OTk5OTg4NjYiLCJwcm9maWxlUGljdHVyZSI6bnVsbCwiYWN0aXZlIjp0cnVlLCJpYXQiOjE3MzYyNzQ3NzQsImV4cCI6MTczNjI4OTE3NH0.1sM2WB3nLBHzFbRxt8yoNs1pHfbSa2o4w1b6gF5FOoo


### GET PERMISSIONS
GET http://localhost:3000/permissions
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDg4Zjc1LTQ0YjYtNGM1Zi05ZTE5LTZkMGU2MzE4OGMxZiIsIm5hbWUiOiJqb2FvIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsInBob25lTnVtYmVyIjoiNTE5OTk5OTg4NjYiLCJwcm9maWxlUGljdHVyZSI6bnVsbCwiYWN0aXZlIjp0cnVlLCJpYXQiOjE3MzYzNjM4NDMsImV4cCI6MTczNjM3ODI0M30.YZF4T9wJ5MqPfjLOOGJanJTqkAwyRsNZfpFKFHUj334

### GET PERMISSIONS/:id
GET http://localhost:3000/permissions/8f753a61-cbb4-4e23-8eb1-e7e8212d3330
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDg4Zjc1LTQ0YjYtNGM1Zi05ZTE5LTZkMGU2MzE4OGMxZiIsIm5hbWUiOiJqb2FvIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsInBob25lTnVtYmVyIjoiNTE5OTk5OTg4NjYiLCJwcm9maWxlUGljdHVyZSI6bnVsbCwiYWN0aXZlIjp0cnVlLCJpYXQiOjE3MzYzNjM4NDMsImV4cCI6MTczNjM3ODI0M30.YZF4T9wJ5MqPfjLOOGJanJTqkAwyRsNZfpFKFHUj334


### POST PERMISSIONS
POST http://localhost:3000/permissions/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDg4Zjc1LTQ0YjYtNGM1Zi05ZTE5LTZkMGU2MzE4OGMxZiIsIm5hbWUiOiJqb2FvIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsInBob25lTnVtYmVyIjoiNTE5OTk5OTg4NjYiLCJwcm9maWxlUGljdHVyZSI6bnVsbCwiYWN0aXZlIjp0cnVlLCJpYXQiOjE3MzYzNjM4NDMsImV4cCI6MTczNjM3ODI0M30.YZF4T9wJ5MqPfjLOOGJanJTqkAwyRsNZfpFKFHUj334

{
  "name": "permissao_teste",
  "descrition": "permissão de teste"
}

### PUT PERMISSIONS
PUT  http://localhost:3000/permissions/8f753a61-cbb4-4e23-8eb1-e7e8212d3330
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDg4Zjc1LTQ0YjYtNGM1Zi05ZTE5LTZkMGU2MzE4OGMxZiIsIm5hbWUiOiJqb2FvIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsInBob25lTnVtYmVyIjoiNTE5OTk5OTg4NjYiLCJwcm9maWxlUGljdHVyZSI6bnVsbCwiYWN0aXZlIjp0cnVlLCJpYXQiOjE3MzYzNjM4NDMsImV4cCI6MTczNjM3ODI0M30.YZF4T9wJ5MqPfjLOOGJanJTqkAwyRsNZfpFKFHUj334

{
  "name": "permissao_testex",
  "descrition": "permissão de teste",
  "active": false
}

### DELETE PERMISSIONS
DELETE http://localhost:3000/permissions/8f753a61-cbb4-4e23-8eb1-e7e8212d3330
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFjZDg4Zjc1LTQ0YjYtNGM1Zi05ZTE5LTZkMGU2MzE4OGMxZiIsIm5hbWUiOiJqb2FvIiwiZW1haWwiOiJqb2FvQHRlc3RlLmNvbSIsInBob25lTnVtYmVyIjoiNTE5OTk5OTg4NjYiLCJwcm9maWxlUGljdHVyZSI6bnVsbCwiYWN0aXZlIjp0cnVlLCJpYXQiOjE3MzY0NDUwMzUsImV4cCI6MTczNjQ1OTQzNX0.e3XTj2tC813S04Qo-c8Weczf-zPmuDpRt5ynLzrslD0
