GET http://localhost:3000

###
GET http://localhost:3000/ping

###
GET http://localhost:3000/user/list

###
POST http://localhost:3000/users/register
content-type: application/json

{
  "name": "samples",
  "email": "teste2@teste.com",
  "password": "123456",
  "phoneNumber": "51999998877"
}
